queries = [
 "quick brown fox",
 "lazy dog",
 "jumps over",
 "the fence",
 "hello world",
 "artificial intelligence",
 "machine learning",
 "natural language processing",
 "deep learning",
 "neural networks",
 "computer vision",
 "data science",
 "big data",
 "internet of things",
 "cloud computing",
 "cybersecurity",
 "software engineering",
 "web development",
 "mobile development",
 "game development",
 "human computer interaction",
 "user experience",
 "user interface",
 "information retrieval",
 "information extraction",
 "text mining",
 "sentiment analysis",
 "topic modeling",
 "machine translation",
 "speech recognition",
 "text summarization",
 "question answering",
 "chatbot",
 "virtual assistant",
 "augmented reality",
 "virtual reality",
 "robotics",
 "autonomous vehicles",
 "drones",
 "3D printing",
 "blockchain",
 "cryptocurrency",
 "internet finance",
 "fintech",
 "e-commerce",
 "social media",
 "online advertising",
 "digital marketing",
 "search engine optimization",
 "content marketing",
 "email marketing",
 "social media marketing",
 "mobile marketing",
 "video marketing",
 "influencer marketing",
 "performance marketing",
 "affiliate marketing",
 "email marketing",
 "direct marketing",
 "telemarketing",
 "sales enablement",
 "customer relationship management",
 "customer service",
 "help desk",
 "technical support",
 "call center",
 "customer success",
 "product management",
 "project management",
 "agile methodology",
 "scrum",
 "kanban",
 "lean startup",
 "design thinking",
 "user-centered design",
 "interaction design",
 "visual design",
 "graphic design",
 "web design",
 "UX design",
 "UI design",
 "front-end development",
 "back-end development",
 "full-stack development",
 "DevOps",
 "cloud engineering",
 "data engineering",
 "machine learning engineering",
 "artificial intelligence engineering",
 "software engineering manager",
 "project manager",
 "product manager",
 "technical lead",
 "team lead",
 "software architect",
 "solutions architect",
 "data scientist",
 "data analyst",
 "business analyst",
 "data engineer",
 "machine learning engineer",
 "artificial intelligence engineer",
 "software developer",
 "web developer",
 "mobile developer",
 "game developer",
 "cybersecurity engineer",
 "network engineer",
 "cloud engineer",
 "DevOps engineer",
 "database administrator",
 "system administrator",
 "IT support specialist",
 "help desk technician",
 "technical support engineer",
 "IT consultant",
 "management consultant",
 "business consultant",
 "strategy consultant",
 "operations consultant",
 "financial consultant",
 "marketing consultant",
 "sales consultant",
 "HR consultant",
 "IT recruiter",
 "technical recruiter",
 "executive recruiter",
 "headhunter",
 "recruiter",
 "hiring manager",
 "talent acquisition",
 "human resources",
 "HR generalist",
 "HR specialist",
 "HR manager",
 "HR director",
 "chief human resources officer",
 "chief people officer",
 "chief operating officer",
 "chief financial officer",
 "chief technology officer",
 "chief information officer",
 "chief executive officer",
 "chief marketing officer",
 "chief product officer",
 "chief data officer",
 "chief security officer",
 "chief risk officer",
 "chief compliance officer",
 "general counsel",
 "legal counsel",
 "lawyer",
 "attorney",
 "paralegal",
 "legal assistant",
 "accountant",
 "auditor",
 "tax accountant",
 "financial analyst",
 "investment banker",
 "wealth manager",
 "financial advisor",
 "insurance agent",
 "real estate agent",
 "sales representative",
 "account executive",
 "sales manager",
 "sales director",
 "sales leader",
 "customer success manager",
 "customer success representative",
 "customer service representative",
 "help desk agent",
 "technical support specialist",
 "project manager",
 "product manager",
 "program manager",
 "scrum master",
 "agile coach",
 "business analyst",
 "data analyst",
 "data scientist",
 "machine learning engineer",
 "artificial intelligence engineer",
 "software engineer",
 "web developer",
 "mobile developer",
 "game developer",
 "cybersecurity engineer",
 "network engineer",
 "cloud engineer",
 "DevOps engineer",
 "database administrator",
 "system administrator",
 "IT support specialist",
 "help desk technician",
 "technical support engineer",
 "IT consultant",
 "management consultant",
 "business consultant",
 "strategy consultant",
 "operations consultant",
 "financial consultant",
 "marketing consultant",
 "sales consultant",
 "HR consultant",
 "IT recruiter",
 "technical recruiter",
 "executive recruiter",
 "headhunter",
 "recruiter",
 "hiring manager",
 "talent acquisition",
 "human resources",
 "HR generalist",
 "HR specialist",
 "HR manager",
 "HR director",
 "chief human resources officer",
 "chief people officer",
 "chief operating officer",
 "chief financial officer",
 "chief technology officer",
 "chief information officer",
 "chief executive officer",
 "chief marketing officer",
 "chief product officer",
 "chief data officer",
 "chief security officer",
 "chief risk officer",
 "chief compliance officer",
 "general counsel",
 "legal counsel",
 "lawyer",
 "attorney",
 "paralegal",
 "legal assistant",
 "accountant",
 "auditor",
 "tax accountant",
 "financial analyst",
 "investment banker",
 "wealth manager",
 "financial advisor",
 "insurance agent",
 "real estate agent",
 "sales representative",
 "account executive",
 "sales manager",
 "sales director",
 "sales leader",
 "customer success manager",
 "customer success representative",
 "customer service representative",
 "help desk agent",
 "technical support specialist",
 "project manager",
 "product manager",
 "program manager",
 "scrum master",
 "agile coach",
 "business analyst",
 "data analyst",
 "data scientist",
 "machine learning engineer",
 "artificial intelligence engineer",
 "software engineer",
 "web developer",
 "mobile developer",
 "game developer",
 "cybersecurity engineer",
 "network engineer",
 "cloud engineer",
 "DevOps engineer",
 "database administrator",
 "system administrator",
 "IT support specialist",
 "help desk technician",
 "technical support engineer",
 "IT consultant",
 "management consultant",
 "business consultant",
 "strategy consultant",
 "operations consultant",
 "financial consultant",
 "marketing consultant",
 "sales consultant",
 "HR consultant",
 "IT recruiter",
 "technical recruiter",
 "executive recruiter",
 "headhunter",
 "recruiter",
 "hiring manager",
 "talent acquisition",
 "human resources ",
 "wine taster",
 "astronaut"
]
